#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : "Neuromatch Academy: Computational Neuroscience"  # The title of the book. Will be placed in the left navbar.
author                      : Neuromatch  # The author of the book
copyright                   : ""  # Copyright year to be placed in the footer
logo                        : tutorials/static/nma-logo-square-4xp.png  # A path to the book logo
only_build_toc_files        : true


#######################################################################################
# Execution settings
execute:
  execute_notebooks         : force # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  cache                     : ""    # A path to the jupyter cache that will be used to store execution artifacts. Defaults to `_build/.jupyter_cache/`
  exclude_patterns          : [Bonus_Autoencoders/Bonus_Tutorial1.ipynb, Bonus_Autoencoders/Bonus_Tutorial2.ipynb, Bonus_Autoencoders/Bonus_Tutorial2.ipynb]    # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)
  timeout                   : 360    # The maximum time (in seconds) each notebook cell is allowed to run.
  run_in_temp               : false # If `True`, then a temporary directory will be created and used as the command working directory (cwd),
                                    # otherwise the notebook's parent directory will be the cwd.
  allow_errors              : true # If `False`, when a code cell raises an error the execution is stopped, otherwise all cells are always run.
  stderr_output             : show  # One of 'show', 'remove', 'remove-warn', 'warn', 'error', 'severe'

# Parse and render settings
parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - dollarmath
    - html_image
sphinx:
  config:
    html_show_copyright: false
#######################################################################################
# HTML-specific settings
html:
  favicon                   : tutorials/static/nma-logo-square-4xp.png  # A path to a favicon image
  use_edit_page_button      : false  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : true  # Whether to add a link to your repository button
  use_issues_button         : true  # Whether to add an "open an issue" button
  extra_navbar              : Powered by <a href="https://jupyterbook.org">Jupyter Book</a>  # Will be displayed underneath the left navbar.
  extra_footer              : ""  # Will be displayed underneath the footer.
  google_analytics_id       : ""  # A GA id that can be used to track book views.
  home_page_in_navbar       : true  # Whether to include your home page in the left Navigation Bar
  baseurl                   : ""  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  comments:
    hypothesis              : false
    utterances              : false
  extra_footer : |
    <div>
    <a href="http://creativecommons.org/licenses/by/4.0/"><img src="https://i.creativecommons.org/l/by/4.0/88x31.png"></a>
    <a href="https://opensource.org/licenses/BSD-3-Clause"><img src="https://camo.githubusercontent.com/9b9ea65d95c9ef878afa1987df65731d47681336/68747470733a2f2f696d672e736869656c64732e696f2f707970692f6c2f736561626f726e2e737667"></a>
    The contents of this repository are shared under the <a href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.
    Software elements are additionally licensed under the <a href="https://opensource.org/licenses/BSD-3-Clause">BSD (3-Clause) License</a>.
    </div>
#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface        : classic  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : ""  # The URL of the BinderHub (e.g., https://mybinder.org)
  jupyterhub_url            : ""  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  thebe                     : false  # Add a thebe button to pages (requires the repository to run on Binder)
  colab_url                 : "" # The URL of Google Colab (https://colab.research.google.com)

repository:
  url                       : https://github.com/NeuromatchAcademy/course-content  # The URL to your book's repository
  path_to_book              : book  # A path to your book's folder, relative to the repository root.
  branch                    : main  # Which branch of the repository should be used when creating links
